export const symbolsRu = [
  {symbol: 'ё', shift: 'Ё', caps: 'Ё', keyCode: 96},
  {symbol: '1', shift: '!', keyCode: 49},
  {symbol: '2', shift: '"', keyCode: 50},
  {symbol: '3', shift: '№', keyCode: 51},
  {symbol: '4', shift: ';', keyCode: 52},
  {symbol: '5', shift: '%', keyCode: 53},
  {symbol: '6', shift: ':', keyCode: 54},
  {symbol: '7', shift: '?', keyCode: 55},
  {symbol: '8', shift: '*', keyCode: 56},
  {symbol: '9', shift: '(', keyCode: 57},
  {symbol: '0', shift: ')', keyCode: 48},
  {symbol: '-', shift: '_', keyCode: 45},
  {symbol: '=', shift: '+', keyCode: 61},
  {symbol: 'Backspace', specClass: 'backspace', shift: '', keyCode: 8},
  {symbol: 'Tab', specClass: 'tab', shift: '', keyCode: 9},
  {symbol: 'й', shift: 'Й', caps: 'Й', keyCode: 81},
  {symbol: 'ц', shift: 'Ц', caps: 'Ц', keyCode: 87},
  {symbol: 'у', shift: 'У', caps: 'У', keyCode: 69},
  {symbol: 'к', shift: 'К', caps: 'К', keyCode: 82},
  {symbol: 'е', shift: 'Е', caps: 'Е', keyCode: 84},
  {symbol: 'н', shift: 'Н', caps: 'Н', keyCode: 89},
  {symbol: 'г', shift: 'Г', caps: 'Г', keyCode: 85},
  {symbol: 'ш', shift: 'Ш', caps: 'Ш', keyCode: 73},
  {symbol: 'щ', shift: 'Щ', caps: 'Щ', keyCode: 79},
  {symbol: 'з', shift: 'З', caps: 'З', keyCode: 80},
  {symbol: 'х', shift: 'Х', caps: 'Х', keyCode: 219},
  {symbol: 'ъ', shift: 'Ъ', caps: 'Ъ', keyCode: 221},
  {symbol: ' \\ ', shift: '/', keyCode: 220},
  {symbol: 'Del', specClass: 'del', shift: '', keyCode: 46},
  {symbol: 'Caps', specClass: 'caps', shift: '', keyCode: 20},
  {symbol: 'ф', shift: 'Ф', caps: 'Ф', keyCode: 65},
  {symbol: 'ы', shift: 'Ы', caps: 'Ы', keyCode: 83},
  {symbol: 'в', shift: 'В', caps: 'В', keyCode: 68},
  {symbol: 'a', shift: 'А', caps: 'А', keyCode: 70},
  {symbol: 'п', shift: 'П', caps: 'П', keyCode: 71},
  {symbol: 'р', shift: 'Р', caps: 'Р', keyCode: 72},
  {symbol: 'о', shift: 'О', caps: 'О', keyCode: 74},
  {symbol: 'л', shift: 'Л', caps: 'Л', keyCode: 75},
  {symbol: 'д', shift: 'Д', caps: 'Д', keyCode: 76},
  {symbol: 'ж', shift: 'Ж', caps: 'Ж', keyCode: 186},
  {symbol: 'э', shift: 'Э', caps: 'Э', keyCode: 222},
  {symbol: 'Enter', specClass: 'enter', shift: '', keyCode: 13},
  {symbol: 'Shift', specClass: 'shift', shift: '', keyCode: 16},
  {symbol: 'я', shift: 'Я', caps: 'Я', keyCode: 90},
  {symbol: 'ч', shift: 'Ч', caps: 'Ч', keyCode: 88},
  {symbol: 'с', shift: 'С', caps: 'С', keyCode: 67},
  {symbol: 'м', shift: 'М', caps: 'М', keyCode: 86},
  {symbol: 'и', shift: 'И', caps: 'И', keyCode: 66},
  {symbol: 'т', shift: 'Т', caps: 'Т', keyCode: 78},
  {symbol: 'ь', shift: 'Ь', caps: 'Ь', keyCode: 77},
  {symbol: 'б', shift: 'Б', caps: 'Б', keyCode: 188},
  {symbol: 'ю', shift: 'Ю', caps: 'Ю', keyCode: 190},
  {symbol: '.', shift: ',', caps: '.', keyCode: 191},
  {symbol: '&#8593;', shift: '&#8593;', caps: '&#8593;', keyCode: 38},
  {symbol: 'Shift', specClass: 'shift', shift: '', keyCode: 16},
  {symbol: 'Ctrl', specClass: 'ctrl', shift: '', keyCode: 17},
  {symbol: 'Win', specClass: 'win', shift: '', keyCode: 91},
  {symbol: 'Alt', specClass: 'alt', shift: '', keyCode: 18},
  {symbol: 'Space', specClass: 'space', shift: '', keyCode: 32},
  {symbol: 'Alt', specClass: 'alt', shift: '', keyCode: 18},
  {symbol: '&#8592;', shift: '&#8592;', caps: '&#8592;', keyCode: 37},
  {symbol: '&#8595;', shift: '&#8595;', caps: '&#8595;', keyCode: 40},
  {symbol: '&#8594;', shift: '&#8594;', caps: '&#8594;', keyCode: 39},
  {symbol: 'Ctrl', specClass: 'ctrl', shift: '', keyCode: 17},
]

export const symbolsEn = [
  {symbol: '`', shift: '~', caps: '`', keyCode: 192},
  {symbol: '1', shift: '!', keyCode: 49},
  {symbol: '2', shift: '"', keyCode: 50},
  {symbol: '3', shift: '№', keyCode: 51},
  {symbol: '4', shift: ';', keyCode: 52},
  {symbol: '5', shift: '%', keyCode: 53},
  {symbol: '6', shift: ':', keyCode: 54},
  {symbol: '7', shift: '?', keyCode: 55},
  {symbol: '8', shift: '*', keyCode: 56},
  {symbol: '9', shift: '(', keyCode: 57},
  {symbol: '0', shift: ')', keyCode: 48},
  {symbol: '-', shift: '_', keyCode: 45},
  {symbol: '=', shift: '+', keyCode: 61},
  {symbol: 'Backspace', specClass: 'backspace', shift: '', keyCode: 8},
  {symbol: 'Tab', specClass: 'tab', shift: '', keyCode: 9},
  {symbol: 'q', shift: 'Q', caps: 'Q', keyCode: 81},
  {symbol: 'w', shift: 'W', caps: 'W', keyCode: 87},
  {symbol: 'e', shift: 'E', caps: 'E', keyCode: 69},
  {symbol: 'r', shift: 'R', caps: 'R', keyCode: 82},
  {symbol: 't', shift: 'T', caps: 'T', keyCode: 84},
  {symbol: 'y', shift: 'Y', caps: 'Y', keyCode: 89},
  {symbol: 'u', shift: 'U', caps: 'U', keyCode: 85},
  {symbol: 'i', shift: 'I', caps: 'I', keyCode: 73},
  {symbol: 'o', shift: 'O', caps: 'O', keyCode: 79},
  {symbol: 'p', shift: 'P', caps: 'P', keyCode: 80},
  {symbol: '[', shift: '[', caps: '[', keyCode: 219},
  {symbol: ']', shift: ']', caps: ']', keyCode: 221},
  {symbol: ' \\ ', shift: '/', keyCode: 220},
  {symbol: 'Del', specClass: 'del', shift: '', keyCode: 46},
  {symbol: 'Caps', specClass: 'caps', shift: '', keyCode: 20},
  {symbol: 'a', shift: 'A', caps: 'A', keyCode: 65},
  {symbol: 's', shift: 'S', caps: 'S', keyCode: 83},
  {symbol: 'd', shift: 'D', caps: 'D', keyCode: 68},
  {symbol: 'f', shift: 'F', caps: 'F', keyCode: 70},
  {symbol: 'g', shift: 'G', caps: 'G', keyCode: 71},
  {symbol: 'h', shift: 'H', caps: 'H', keyCode: 72},
  {symbol: 'j', shift: 'J', caps: 'J', keyCode: 74},
  {symbol: 'k', shift: 'K', caps: 'K', keyCode: 75},
  {symbol: 'l', shift: 'L', caps: 'L', keyCode: 76},
  {symbol: ';', shift: ';', caps: ';', keyCode: 186},
  {symbol: '\'', shift: '"', caps: '\'', keyCode: 222},
  {symbol: 'Enter', specClass: 'enter', shift: '', keyCode: 13},
  {symbol: 'Shift', specClass: 'shift', shift: '', keyCode: 16},
  {symbol: 'z', shift: 'Z', caps: 'Z', keyCode: 90},
  {symbol: 'x', shift: 'X', caps: 'X', keyCode: 88},
  {symbol: 'c', shift: 'C', caps: 'C', keyCode: 67},
  {symbol: 'v', shift: 'V', caps: 'V', keyCode: 86},
  {symbol: 'b', shift: 'B', caps: 'B', keyCode: 66},
  {symbol: 'n', shift: 'N', caps: 'N', keyCode: 78},
  {symbol: 'm', shift: 'M', caps: 'M', keyCode: 77},
  {symbol: ',', shift: '<', caps: ',', keyCode: 188},
  {symbol: '.', shift: '>', caps: '.', keyCode: 190},
  {symbol: '/', shift: '?', caps: '/', keyCode: 191},
  {symbol: '&#8593;', shift: '&#8593;', caps: '&#8593;', keyCode: 38},
  {symbol: 'Shift', specClass: 'shift', shift: '', keyCode: 16},
  {symbol: 'Ctrl', specClass: 'ctrl', shift: '', keyCode: 17},
  {symbol: 'Win', specClass: 'win', shift: '', keyCode: 91},
  {symbol: 'Alt', specClass: 'alt', shift: '', keyCode: 18},
  {symbol: 'Space', specClass: 'space', shift: '', keyCode: 32},
  {symbol: 'Alt', specClass: 'alt', shift: '', keyCode: 18},
  {symbol: '&#8592;', shift: '&#8592;', caps: '&#8592;', keyCode: 37},
  {symbol: '&#8595;', shift: '&#8595;', caps: '&#8595;', keyCode: 40},
  {symbol: '&#8594;', shift: '&#8594;', caps: '&#8594;', keyCode: 39},
  {symbol: 'Ctrl', specClass: 'ctrl', shift: '', keyCode: 17},
]

// export default document.onkeypress = function (event) {
//  return (
//    console.log(event.charCode),
//   console.log(event.key)
//  )
// }

